### ISSUE TITLE
Add back button onto the pages

### ISSUE THREAD

**Issue by nicholasericksen** [nicholasericksen/GHV-data#10]
We should have a back button in the top right corner to be able to go between menu levels

**Comment by hhassan1230** [comment]
Okay Let me see if I can do this.

**Comment by Sloanie81** [comment]
Hi, I'm Jennifer.  I created the climate change curriculum for Groundwork Hudson Valley.
Could we do two buttons on top corner.  One for Home Menu and one that brings you just one step back (that you can click on from any menu?)

**Comment by nicholasericksen** [comment]
Yup we will be able to that!
