### ISSUE TITLE
Sea Level NOAA Interactive

### ISSUE THREAD

**Issue by Sloanie81** [nicholasericksen/GHV-data#14]
The embed works to bring you to the first screen, but then you can't actually get to the imaging interactive content from there... (Launch Button not showing for some reason)
Can you embed directly from this site:
https://coast.noaa.gov/slr/#/layer/slr

**Comment by Sloanie81** [comment]
OR http://bit.ly/2rlyoM5

**Comment by nicholasericksen** [comment]
We have fixed this by going right to the interactive and bypassing the first screen.
