### ISSUE TITLE
CLEAR OUT YOUR DEAD

### ISSUE THREAD

**Issue by sciencebarge** [nicholasericksen/GHV-data#23]
**Dead Links for Fixing or Total Recall:**

**1) Sea Level Rise Local Scenarios: Scenic Hudson Interactive Map** - ISSUE: does not load on Chrome
     Currently Found at Climate Monitoring>>Sea Level Rise>>Sea Level Rise Local Scenarios...

**Comment by nicholasericksen** [comment]
This is gone now
