### ISSUE TITLE
WE CAN REBUILD HIM: WE HAVE THE TECHNOLOGY 

### ISSUE THREAD

**Issue by sciencebarge** [nicholasericksen/GHV-data#24]
Starting with Menu 1, now called **"Climate Science"**

 The "Why Data Matters" video, formerly under another tab (Real Time Climate Monitoring) will be migrated to the top of this Menu (1.1)
______________________________________________________________________________________________________________
The **Climate versus Weather** tab will be migrated from fourth slot to the second slot on this Menu, (1.2)
The content in this tab doesn't need to change.
______________________________________________________________________________________________________________
The **Polar and Glacial Ice** tab will be migrated to Main Menu 2 (now to be called Climate Impact) to the top spot 2.1
All the sub-tabs can be migrated with it (more content will be added, but we'll get to that later)
______________________________________________________________________________________________________________
A NEW tab will be inserted into the 1.3 spot, to be called **"Historical Climate Change: Clues in Trees and Ice"**
It will have a new video added and The NOVA Ice Core Video migrated from "Real Time Climate Monitoring" to here:
1.3.1:  **"Dendrichronology: What tree cores tell us about local climate history."** (You Tube link: https://youtu.be/-Vfg4GieRTc)
1.3.2: **"Climate History in Ice Cores (NOVA video segment: Extreme Ice)"**  (downloaded video migrated from Real Time Climate Monitoring to here)
_______________________________________________________________________________________________________________
1.4 **Real Time Climate Monitoring** tab will now take the fourth spot in Menu 1.
The "Why Climate Data Matters" video and the NOVA video have already been migrated out of this tab.

1.4.1 **NASA Climate Time Machine** will stay and move to the top of this Menu
1.4.2 **Local Weather and River Conditions (HRECOS Monitoring System)** will be NEW content. Hopefully the graphing tool can be embedded.
_______________________________________________________________________________________________________________
1.5 **Natural Forces: volcanoes, sunspots, and meteors, oh my!** is a NEW tab with NEW content

1.5.1 **Natural Cycles: Evidence of Change (Source: Video by National Academies of Science Engineering and Medicine) ** is a YouTube link: [https://youtu.be/2_10jtPCjQw](url)
1.5.2  **Natural Climate Forces** is a slideshow with captions.  The pictures and captions will be in the folder
1.5.3 **NASA Video Comparing Natural & Human Factors** is a migrated tab originally found under Global Temperatures and Greenhouse Gas Concentrations.
______________________________________________________________________________________________________________
1.6 **The Greenhouse Effect and Anthropogenic Warming** is now the NEW NAME for the tab **Global Temperatures and Greenhouse Gas Concentrations**
It will have some new content, and a few tabs that were there that have been migrated out.

1.6.1 **The Greenhouse Effect** slideshow will gain 2 additional pictures with captions (see folder)
1.6.2 **Global Temperature Time Series Map (1884-2012)** is a different version (see folder for DL) that includes a temperature scale.  There are options for sized to DL on NASA's site if this is too big
1.6.3 **CO2 and Global Temperature Correlation (Past 800,000 years)** is renamed from "Historical CO2 and Global Temperature Correlation"  and has a new picture to replace this one (see folder). The caption can remain the same though.  Please make sure the "2" on CO2 is subscripted.
1.6.4 **Natural and Human Factors** is a NEW tab and will contain only a single picture with a caption (see folder)
1.6.5 **Post Industrial CO2 and Temperature (1850-2015)** (with the 2 subscripted) is a rename from "Modern Era CO2 and Temperature Correlation) and can keep the caption.  Check the folder to see if my new Download is higher resolution that the picture currently on the app.

**Comment by sciencebarge** [comment]
Menu 2: **Climate Change Impact**
Much of this menu is migrated information from other tabs on the app.  The names of tabs will be shortened for simplicity and aesthetic, too.  It will have 7 tabs

2.1: Polar and Glacial Ice has been migrated from Menu 1 to the top spot here.

2.1.1  **Glacial Melt: NASA Images of Change** is a rename from "Images of Change NASA Glacier Melt".  You can ignore the slideshow images in the folder. (I'll use them in the curriculum instead)
2.1.2 **Antarctic & Greenland Land Ice**  needs a name correction. Antarctic has 2 "c"s.  I'll post captions for this slideshow later.
2.1.3 **National Snow & Ice Data Center (NSIDC) Charctic Interactive Sea Ice Graph** has a slight name change to reflect SEA ice... This link doesn't always seem to load well...?
2.1.4 **Arctic Sea Ice and Albedo Effect** is a NEW tab for a slideshow with captions (see folder) This includes an mp4 movie file, so if it cannot go in a slideshow, then we will have to break out another tab for the movie and one for the two images.
_______________________________________________________________________________________________________________

**Comment by nicholasericksen** [comment]
Menu 1 is now updated and complete! Take a look and let me know
