### ISSUE TITLE
TRY NOT: DO OR DO NOT, THERE IS NO TRY

### ISSUE THREAD

**Issue by sciencebarge** [nicholasericksen/GHV-data#25]
Moving on to Main Menu tab 2: **Climate Impact** 
This menu will consist of the following sub tabs:

**2.1 Polar and Glacial Ice
2.2 Water Cycle and Extreme Weather
2.3 Oceans and Coasts
2.4 Agriculture
2.5 Forest Cover
2.6 Wildlife
2.7 Human Health and Disease**

All of the tabs currently under Main Menu 3: **Adaptation and Resiliency** (Deluge and Drought videos, Freshwater, and Water Contamination) EXCEPT for Water and Energy will be migrated into **2.2 Water Cycle and Extreme Weather**
______________________________________________________________________________________________________________
**2.1 Polar and Glacial Ice**
There was material in the first tab before the changeover that seems to have gone missing... In any case, the new layout will be in a zipped folder.  This Menu will have 4 tabs:

**2.1.1 NASA Images of Change: Muir Glacier** (website: [https://climate.nasa.gov/images-of-change?id=376#376-muir-glacier-melt-alaska] )
**2.1.2 Land Ice Graphs** (slideshow with captions)
**2.1.3 National Snow and Ice Data Center _Ch_arctic Sea Ice Graph** website widget
**2.1.4 Sea Ice** (slideshow with captions)

_______________________________________________________________________________________________________________
**2.2 Water Cycle and Extreme Weather**  I'm still working out the end of this menu... I want to add new images in a slideshow that include the most recent storms from 2017 and 2018.   Most of it will be as it shows up in the zipped folder and pdf file though.  This menu had the content that needs to migrate over that I mentioned up top.

_My main question was whether you could combine the deluge and drought videos into 1 tab as a slideshow. 
 There is also a 3rd video zipped in that folder that is about the water cycle. 
 If not, skip the 3rd video and keep these two on Deluge and Drought.

Follow the pdf for the rest of the tabs
______________________________________________________________________________________________________________
**2.3 Oceans and Coasts**  The New content here will be at the top, with 2  video links about Ocean Acidification (one to youtube, the other downloaded)

The other 3 tabs are the same that you had before (can't find them with the new edits done) and include a widget for NOAA's Digital Coast, the Scenic Hudson Mapping Tool (if we could get it to load correctly) and the antarctica melting slideshow.
_______________________________________________________________________________________________________________

**Comment by nicholasericksen** [comment]
This should be done
