### ISSUE TITLE
Widgets and Links that do not load (DNL)

### ISSUE THREAD

**Issue by sciencebarge** [nicholasericksen/GHV-data#26]
Just went through all the content and here is what needs to be repaired or replaced.  Let me know if you need a replacement, bc I have alternatives for a lot of this content, I think.  All things considered, I'm impressed with how much loads on this first run through! I think if downloaded content isn't playing bc of a space issue, deleting the Scenic Hudson "Yonkers and Hudson Valley Coastline" software should free up a lot of space (see below)

EDIT: It seems a lot of content that doesn't load or are repeat links are bc they were incorrect on my pdf guide.  All the content that you need has already been downloaded and labeled in the folders I emailed you.  So please refer to those folders when making corrections.  That way you don't have to follow links to find downloads first, etc etc.  Also, there were some places where additional pictures for slideshows were added into those folders but not referenced in the pdf guide necessarily.  So cross-referencing the folders is best b/c they are MORE right than the pdf, which has definite errors and omissions.

**Broken widgets or incorrect links in bold:**

>Climate Change Impact
	>>Water Cycle and Extreme Weather
		>>>**Extreme Precipitation (interactive map)**
		>>>**NOAA The State of the Climate**

	>>Oceans and Coasts
		>>>**NOVA Impact of Ocean Acidification** (should be a DL file - repeats previous Youtube 
                      video from ACE)
		>>>**Yonkers and the Hudson Valley Coastline** (dnl - DELETE THIS CONTENT SHOULD SAVE 
                      A LOT OF SPACE - I have a replacement to try out under a new name)
	>>Agriculture
		>>>USDA Plant Hardiness Zone Map (should be a replacement widget on Arbor Day website?)
	>>Wildlife (title change)
		>>>**A Warmer World for Arctic Animals** (dnl)
		>>>**Species Range Change Interactive** (dnl - have DL images we could use instead)
		>>>**Bees are feeling the STING** (video can be downloaded... it loads whole NASA page)
	>>Human Health and Disease
		>>>**Pathways and Regional Vulnerabilities** (images dnl)
		>>>**Air Quality Map Tool**
		>>>**Water Contamination** (image dnl)

>Adaptation and Resilience
	>>The Global Effort
		>>>**Paris Agreement Interactive** (times out while loading)
	>>Coastal Resilience
		>>>**Estuary Model and Coastal Resilience (CURB)** (dnl)
		>>>**Coastal Resilience** (broken link/page symbol in player)
	>>Think Globally, Act Locally
		>>>Emergency Preparedness
			>>>>**Weather Ready Nation Videos** (loads carbon footprint 					 
                                  calculator widget instead)
		>>>Designing Cities for Resilience
			>>>>**Sustainable Cities: Nature Based Solutions** (broken page symbol in player)
			>>>>**Be Water Wise** (images dnl)
		>>>Tracking National Progress
			>>>>**Climate Progress by State Google Map**

**Comment by sciencebarge** [comment]
The video in Climate Impact>>Oceans>>>NOVA Researching Impacts of Ocean Acidification 
can be found in the folder as a DL.  The link in the pdf guide is incorrect.

**Comment by sciencebarge** [comment]
Link under Climate Impact>Agriculture>>>NOAA Drought Monitor

Is it possible to swap this animated gif maps to an embedded widget from NOAA's site found here?:
[https://www.climate.gov/maps-data/data-snapshots/usdroughtmonitor-weekly-ndmc-2012-08-07?theme=Drought]

If the widget won't embed, we can keep the content we have, but this is a better NOAA resource and we are trying to include more of those.

**Comment by sciencebarge** [comment]
Missing link
Climate Impact>>Forests>>>Projected Shift in Forest Types

That should be just after Forest Pest Video.

It'll be this picture (also in folder):
https://www.epa.gov/sites/production/files/2016-06/shiftinforesttypes-large.jpg

**Comment by sciencebarge** [comment]
Incorrect link given for:

Climate Impact>>Wildlife>>>A Warmer World for Arctic Animals

Please refer to the video download in the folder 2.6.1
There is a download for the video about bees too under folder 2.6.3

**Comment by sciencebarge** [comment]
In place of Scenic Hudson River mapping tool, place the following embed under this tab:
>Climate Impact>>Oceans and Coasts>>>Scenic Hudson Estuary Impact from Sea Level Rise

Embed code found on top right under link icon at this site (NO autoplay)
[https://scenichudson.maps.arcgis.com/apps/MapSeries/index.html?appid=9190b7560a574ad69cd91b43e383b203](url)

**Comment by nicholasericksen** [comment]
> The video in Climate Impact>>Oceans>>>NOVA Researching Impacts of Ocean Acidification
> can be found in the folder as a DL. The link in the pdf guide is incorrect.

^*This is updated now and will be live shortly*

> Projected Shift in Forest Types

^*This is updated now*


>Incorrect link given for:Climate Impact>>Wildlife>>>A Warmer World for Arctic AnimalsPlease refer >to the video download in the folder 2.6.1There is a download for the video about bees too under >folder 2.6.3

^*This is done now and will be live shortly*

>In place of Scenic Hudson River mapping tool, place the following embed under this tab:
>Climate Impact>>Oceans and Coasts>>>Scenic Hudson Estuary Impact from Sea Level Rise
>Embed code found on top right under link icon at this site (NO autoplay)

^* This is also updated now*

**Comment by nicholasericksen** [comment]
First comment is now mostly updated. 

In section 3:
Adaptation and Resilience
for links that don't work it doesn't look like there are static image replacements? Is there something to replace the broken links with?

I have tried to review the issues that are not showing or incorrect. If there is preference for better content it is probably not changed yet.  I did not have the time to go through each folder and double check all the content yet.  Please note the most urgent items that are left after your next review.

**Comment by nicholasericksen** [comment]
I have just done a quick check of section 3 and all sections are showing content on each page at least
