### ISSUE TITLE
Title Spelling Corrections

### ISSUE THREAD

**Issue by sciencebarge** [nicholasericksen/GHV-data#27]
>Climate Change Impact
	>>Polar and Glacial Ice
		>>>**Antarctic** & Greenland Land Ice (add c)
		>>>**Arctic** Sea Ice and Albedo Effect (add c)
	>>**Forests** (1 r)
		>>**Forest** Pest Video (1 r)
	>>Animal Ranges --> **Wildlife** (name change)
		>>>A Warmer World for **Arctic** Animals (add c)

**Comment by nicholasericksen** [comment]
These have now been corrected and will be live shortly
