### ISSUE TITLE
Add Content

### ISSUE THREAD

**Issue by nicholasericksen** [nicholasericksen/GHV-data#6]
We now have content to enter into the pages.

**Comment by nicholasericksen** [comment]
Content is still not finalized all the way.  Waiting for the exact copy and graphics

**Comment by nicholasericksen** [comment]
[GHV-mock.pdf](https://github.com/nicholasericksen/GHV-data/files/926850/GHV-mock.pdf)

Mock now attached for v1

**Comment by Sloanie81** [comment]
I have some VERY large files from Scenic Hudson for Yonkers coast sea level rise but they are TIFF files and I cannot open them to see how they work.  I'm also concerned at how large they are.  Should we delete this content or maybe if you can view TIFF we can create 1-2 static images for use there instead?

**Comment by nicholasericksen** [comment]
I think we are all on the same page now as to what content we have and any limitations we have.  I will close this ticket for now.
